### ISSUE TITLE
Kan inte spara

### ISSUE THREAD

**Issue by bergh-io** [JoakimSoderberg/sketchup-svg-outline-plugin#1]
Jag kan inte få den att spara till svg. När jag trycker på Save händer det helt enkelt inget alls. Har du någon idé om vad det kan bero på?

**Comment by JoakimSoderberg** [comment]
Hej,

Är du säker på att det är min version du har installerad till att börja med? Se till att du garanterat tagit bort någon äldre version först. I den här versionen ska du bara få en ikon som heter SVG. Inte den med en fluga på...

Det var nämligen exakt det problemet jag hade som fick mig att fixa det till att börja med. Att save inte fungerade.

Sen är det tyvärr väldigt mycket svart magi med hur jag fixade detta plugin. Tydligen så skriver sketchup själv om plugin filerna lite automagiskt på något sätt. 

Jag ändrade väldigt få rader för att fixa problemet. Men sen insåg jag efter jag kört och testat min fix, att Sketchup även automatiskt skrev om en del filer. Antar att det beror på att de vill att plugin ska fungera i den nya versionen automatiskt:

https://github.com/JoakimSoderberg/sketchup-svg-outline-plugin/commit/2984da98ce7503ff99d8ef722f6e2168d40871e9

Och pga det så är jag inte 100% säker på vilka av mina ändringar som fixade problemet :)

Jag började däremot med att bara visa popups på en massa ställen. Till att börja med i onOk för save-knappen.

**Comment by bergh-io** [comment]
Hej! Tack för snabbt svar!

Jag installerade originalet först men hittade sedan din efter lite sökningar på varför det inte fungerade.
Jag hittade inget sätt att avinstallera originalet så jag testade att installera din version över den så att säga. Enligt SketchUp så gick installationen bra men tydligen blev det vajj iallafall. Jag lyckades nu ta bort filerna manuellt och sedan installera din version igen och nu fungerar det som det ska! 

Stort tack för snabbt svar och framför allt för att du fixat den här versionen!

**Comment by JoakimSoderberg** [comment]
Bra att det löste sig. Jag ska lägga till i README om att man ska se till att den gamla versionen verkligen är borta.
