### ISSUE TITLE
Button doesn't seem to do anything

### ISSUE THREAD

**Issue by JWMage** [JoakimSoderberg/sketchup-svg-outline-plugin#2]
I double checked to make sure that the old version was deleted, but the SVG button still doesn't seem to do anything.

Any suggestions on what I could try?

This would be a great extension to have working. Thanks for your effort.

**Comment by JWMage** [comment]
I was thinking about the issue and realized that the button wasn't working because I never selected a face in Sketchup. In order for it to export a face, one has to be selected. Since it didn't give me a warning message, I assumed it was broken... I was wrong! It works. :+1: 

Perhaps it would be helpful to link to the original author's tutorial:
http://www.instructables.com/id/SketchUp-Inkscape-and-Ponoko-Laser-Cutting/step3/Using-the-SVG-Export-Plugin/

**Comment by JoakimSoderberg** [comment]
Ah, nice that you solved it yourself! :)
