### ISSUE TITLE
extension installation fails silently

### ISSUE THREAD

**Issue by RichMorin** [JoakimSoderberg/sketchup-svg-outline-plugin#4]
After installing the original plugin (on SketchUp Make 15.3.329), I removed the flightsofideas.\* files from the Plugins directory. I then downloaded, renamed, and moved sketchup-svg-outline-plugin-master.rbz into the directory.

I have attempted to install the extension, using SketchUp > Preferences > Extensions. No warnings or errors appear, but the extension does not appear to be installed.  It isn't on the list and no visible GUI elements appear to change.

**Comment by donkjr** [comment]
I really need this plugin for my laser cutter needs !
I have a similiar problem. I loaded the plugin via the extension manager and it is not visible in SU. I looked at the plugin install directory and it is there. However it does not show up in the extension directory in SU.
I noticed that the plugin requires:
require 'sketchup.rb'
require 'extensions.rb'
require 'LangHandler.rb'
I am not a ruby programmer but are these includes that I need to install.
I don't see these .rb files loaded anywhere is this the problem if so where do I get these.

**Comment by JoakimSoderberg** [comment]
Hello,

Sorry I had missed this issue.... Are you following the instructions in the README step by step? All of it?

Those ruby files are a part of Sketchup itself, so if you have that they should be there.

**Comment by JoakimSoderberg** [comment]
@RichMorin What you describe doing is not exactly how the instructions are. So please remove the .rbz file and follow this: https://github.com/JoakimSoderberg/sketchup-svg-outline-plugin#installation

**Comment by JoakimSoderberg** [comment]
> I loaded the plugin via the extension manager and it is not visible in SU. I looked at the plugin install directory and it is there.

@donkjr To be clear, did you follow these steps exactly?:  https://github.com/JoakimSoderberg/sketchup-svg-outline-plugin#installation

**Comment by JoakimSoderberg** [comment]
Ok, I just tried this on my new computer. I downloaded the new Sketchup Make (Also called Sketchup 2016) on OSX.

Sketchup are not very nice when it comes to plugin writers it seems, each new version breaks stuff it seems. Anyway, before it worked fine to simply download the `.zip` from the releases here on github. Then rename it to `.rbz`. Then install it in sketchup.

However, all that still works, and sketchup says everything is fine... But it is not. Stupid broken program. Basically it doesn't check that the files are put in the correct position, and the extension will not show up in sketchup. What you need to do is to move the files one level "down" into the Plugin directory, then it works.... I made some pictures to explain this:

# Here is how sketchup is broken (and how to fix):

First I download the `.zip` to some location, and rename it to `.rbz`. DO NOT PUT IT IN THE PLUGINS DIRECTORY

This is what the plugin directory looks like before installing. Again location of this dir: http://help.sketchup.com/en/article/38583
<img width="423" alt="screenshot 2016-01-26 19 17 06" src="https://cloud.githubusercontent.com/assets/1446626/12590264/4c8ff2f0-c462-11e5-8f8c-c0f2ade2c8fb.png">

Now i go into sketchup and install it:
<img width="262" alt="screenshot 2016-01-26 19 17 32" src="https://cloud.githubusercontent.com/assets/1446626/12590300/8649aaea-c462-11e5-879e-70888703d0e8.png">

<img width="565" alt="screenshot 2016-01-26 19 17 44" src="https://cloud.githubusercontent.com/assets/1446626/12590305/8af891fa-c462-11e5-90b0-2fca279625b5.png">

Find the file I rename to `.rbz`:
<img width="422" alt="screenshot 2016-01-26 19 18 28" src="https://cloud.githubusercontent.com/assets/1446626/12590311/949bee78-c462-11e5-85e7-8f4ccb7350d0.png">

Yes I trust it:
<img width="430" alt="screenshot 2016-01-26 19 18 41" src="https://cloud.githubusercontent.com/assets/1446626/12590328/b19e44c6-c462-11e5-938f-b7d3aebf05b6.png">

SKETCHUP LIES:
<img width="426" alt="screenshot 2016-01-26 19 18 49" src="https://cloud.githubusercontent.com/assets/1446626/12590331/b9fb439e-c462-11e5-85a4-7fc36eef1d0f.png">

# Fixing it

How the plugin folder now looks:
<img width="613" alt="screenshot 2016-01-26 19 19 09" src="https://cloud.githubusercontent.com/assets/1446626/12590341/c3922ab2-c462-11e5-9991-34b72196a94c.png">

What you need to do is to move the files out of the directory
<img width="490" alt="screenshot 2016-01-26 19 19 45" src="https://cloud.githubusercontent.com/assets/1446626/12590347/cbbe830c-c462-11e5-9adb-2bbc4cfcf4c7.png">

Now restart Sketchup, you should see the plugin in preferences. It should be checked:
<img width="559" alt="screenshot 2016-01-26 19 21 08" src="https://cloud.githubusercontent.com/assets/1446626/12590371/f6150734-c462-11e5-9e31-e419340e1989.png">

And you should see the icon
<img width="455" alt="screenshot 2016-01-26 19 21 16" src="https://cloud.githubusercontent.com/assets/1446626/12590380/ff0e028c-c462-11e5-8090-b7e307e3160f.png">

When using it, make sure you click the `...` to set the path explicitly, or it will just fail saving.

**Comment by JoakimSoderberg** [comment]
...

So it turns out github adds an extra folder to the zip. OSX Finder unzips a zip with this folder in the exact same way as it unzips a zip without a folder in it:

`bla.zip` with a folder `bla/` on OSX unpacks all files inside of this to `bla/*` ... Not `bla/bla/*``

`bla.zip` without a folder in it also unzips to `bla/`

Which I found out here:
http://forums.sketchup.com/t/extension-install-broken/19378/6

Anyway, I have now created a new release, with an `.rbz` file I made myself, and not the github generated `.zip` ... this works on Sketchup 2016 for me. Older releases I have no idea, so get the latest.

The new instructions reflect this change.

**Comment by donkjr** [comment]
Sorry if I missed it but where is the new release?
BTW this plugin is awesome it allows me to now use SU with my laser cutter :).

**Comment by JoakimSoderberg** [comment]
https://github.com/JoakimSoderberg/sketchup-svg-outline-plugin/releases/tag/1.2

But yea, I did not write this I just simply made it work with never Sketchup versions.... So I should not get the credit :) The original author never replied to me, so I forked it so others can use it as well

**Comment by donkjr** [comment]
I know you did not write the original but appreciate the fix :)
